### PR TITLE
Remove displayAtCheckout usage

### LINKED ISSUE #24: PMPro_Field::displayAtCheckout is deprecated in v3.4 +
**Describe the bug**
PMPro_Field::displayAtCheckout is deprecated since version 3.4. The replacement for this method is to use PMPro_Field_Group::display() instead.

**To Reproduce**
1. Navigate to the frontend testimonial display form.
2. If WP_DEBUG is enabled and displayed you will see the deprecation warning.

**Expected behavior**
No warnings should be shown. We should support the current method as a fallback if the site is not running a PMPro version with the new PMPro_Field_Group::display method.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://memberlitetheme.com).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by derekashauer**
### All Submissions:

* [X] Have you followed the [Contributing guidelines](https://github.com/strangerstudios/pmpro-pay-by-check/blob/dev/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/pmpro-testimonials/pulls/) for the same update/change?

### Changes proposed in this Pull Request:

Resolves #24 

Remove all usage of now deprecated displayAtCheckout and build form fields

### How to test the changes in this Pull Request:

1. Go to frontend testimonial submission form
2. Submit with debug enabled
3. No more deprecation notices!

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Testimonial submission form fields restructured to no longer use deprecated displayAtCheckout()

### CODE REVIEW

File: includes/classes/pmpro-testimonial-form.php [hunk 1]
```diff
@@ -128,113 +126,160 @@ public function display( $echo = true ) {
...
-										$category_field->displayAtCheckout();
+										if ( $categories ) {
+											$selected_category = isset( $_POST['testimonial_category'] ) ? intval( $_POST['testimonial_category'] ) : '';
+											$required = false;
+											if ( in_array( 'url', $this->required_fields ) ) {
+												$required = true;
+											}
+											?>
+											<div class="<?php echo esc_attr( pmpro_get_element_class( 'pmpro_form_field pmpro_form_field-required pmpro_form_field-select', 'url' ) ); ?>">
+												<label for="url" class="<?php echo esc_attr( pmpro_get_element_class( 'pmpro_form_label' ) ); ?>">
```
Comment (kimcoleman) [inline includes/classes/pmpro-testimonial-form.php:240]: This should be  `for="testimonial_category"`

**Comment by kimcoleman** [comment]
Every field here needs an ID value = to its name value (or matching the label's "for" value.

File: includes/classes/pmpro-testimonial-form.php [hunk 2]
```diff
@@ -98,21 +99,18 @@ public function display( $echo = true ) {
...
-										'textarea',
-										array(
-											'label'        => __( 'Testimonial', 'pmpro-testimonials' ),
-											'required'     => true,
-											'showrequired' => 'label',
-										)
-									);
-									$title_field->displayAtCheckout();
+									
+									<div class="<?php echo esc_attr( pmpro_get_element_class( 'pmpro_form_field pmpro_form_field-required pmpro_form_field-textarea', 'testimonial' ) ); ?>">
```
Comment (kimcoleman) [inline includes/classes/pmpro-testimonial-form.php:103]: This adds the `pmpro_form_field-required` class, but doesn't include a check for whether it is required. We could probably avoid adding that selector here, only because it isn't used by JS (like core PMPro) to show contextual "errors" on form submit.

File: includes/classes/pmpro-testimonial-form.php (hunk 1 above)
Comment (andrewlimaza) [reply includes/classes/pmpro-testimonial-form.php]: Resolved this.

**Review by kimcoleman — APPROVED** [review]
All changes are approved.
